import { CanonicalFact, CanonicalMetric } from "./types";

export const CANONICAL_METRICS: CanonicalMetric[] = [
  {
    id: "metric-msft-copilot-mau",
    name: "Copilot Adoption Scale (MAU)",
    metricDefinition: "Monthly Active Users of Copilot adoption experiences across Viva Engage and Teams.",
    baseline: null,
    finalValue: "1.5M+ MAU",
    measurementPeriod: "May 2025 – Present",
    population: "850+ enterprise tenants globally",
    attribution: "Led design of Copilot Adoption Community experiences",
    approvedPublicWording: "Scaled Copilot adoption to 1.5M+ monthly active users across 850+ enterprise tenants.",
    publicApprovalStatus: "approved",
    verificationStatus: "verified",
    sourceRef: "Microsoft Viva Engage Team Internal Performance & Portfolio Review"
  },
  {
    id: "metric-msft-copilot-wau-growth",
    name: "Copilot Weekly Active User Expansion",
    metricDefinition: "Weekly Active Users participating in Copilot community habits and workflows.",
    baseline: "936K WAU",
    finalValue: "3.4M WAU (3x growth)",
    measurementPeriod: "2025",
    population: "Enterprise Viva Engage & Teams enterprise users",
    attribution: "UX system redesign and Teams integration",
    approvedPublicWording: "Drove 3x growth in Copilot weekly active users, scaling from 936K to 3.4M.",
    publicApprovalStatus: "approved",
    verificationStatus: "verified",
    sourceRef: "Microsoft Copilot Adoption Analytics Dashboard"
  },
  {
    id: "metric-msft-tenant-growth",
    name: "Enterprise Tenant Growth & Engagement",
    metricDefinition: "Multi-tenant enterprise adoption and engagement multiple.",
    baseline: "1.0x baseline",
    finalValue: "2.5x tenant growth, 3x user engagement",
    measurementPeriod: "2025",
    population: "850+ enterprise customers",
    attribution: "Copilot Adoption Community experiences in Viva Engage",
    approvedPublicWording: "Contributed to 2.5x enterprise tenant growth and 3x user engagement.",
    publicApprovalStatus: "approved",
    verificationStatus: "verified",
    sourceRef: "Microsoft Product Impact Review"
  },
  {
    id: "metric-google-anthos-adoption",
    name: "Anthos Product Adoption Lift",
    metricDefinition: "Percentage increase in enterprise product adoption following UX simplification.",
    baseline: "Pre-overhaul baseline",
    finalValue: "+30% adoption acceleration",
    measurementPeriod: "2021 – 2024",
    population: "Google Cloud Anthos enterprise customers",
    attribution: "Lead UX Designer overhaul of Anthos",
    approvedPublicWording: "Accelerated Anthos enterprise adoption by 30% through UX modernization.",
    publicApprovalStatus: "approved",
    verificationStatus: "verified",
    sourceRef: "Google Cloud UX Case Study & OKR Tracking"
  },
  {
    id: "metric-google-anthos-csat",
    name: "Google Cloud Security CSAT Lift",
    metricDefinition: "Customer Satisfaction score improvement across complex cloud security workflows.",
    baseline: "Pre-overhaul CSAT score",
    finalValue: "+25% CSAT boost",
    measurementPeriod: "2021 – 2024",
    population: "Enterprise security engineers and administrators",
    attribution: "Workflows automation and simplified interaction architecture",
    approvedPublicWording: "Boosted CSAT by 25% across cloud security workflows.",
    publicApprovalStatus: "approved",
    verificationStatus: "verified",
    sourceRef: "Google Cloud Customer Satisfaction Metrics"
  }
];

export const CANONICAL_FACTS: CanonicalFact[] = [
  // ── Identity & Core Profile ──
  {
    id: "fact-identity-name",
    category: "identity",
    subject: "Full Name",
    exactClaim: "Vikram Venkatesh",
    searchKeywords: ["who are you", "name", "identity", "vikram", "vikram venkatesh"],
    sourceRef: "vikramtheartist.com portfolio",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Permanent",
    relatedProjects: [],
    relatedTopics: ["profile", "bio"],
    approvedWording: "I am Vikram Venkatesh, a Product Design Leader with 18+ years of global experience."
  },
  {
    id: "fact-identity-title",
    category: "identity",
    subject: "Professional Title & Specialty",
    exactClaim: "Product Design Leader specializing in AI-first enterprise systems and behavioral adoption.",
    searchKeywords: ["title", "role", "design leader", "what do you do", "specialty"],
    sourceRef: "vikramtheartist.com portfolio hero",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Current",
    relatedProjects: ["Copilot Adoption", "AdoptIQ"],
    relatedTopics: ["leadership", "ai-design"],
    approvedWording: "I design AI-first products that feel human, balancing strategic roadmapping with hands-on interaction craft."
  },
  {
    id: "fact-identity-experience-years",
    category: "identity",
    subject: "Years of Experience",
    exactClaim: "18+ years of global product design experience (2007–Present).",
    searchKeywords: ["years of experience", "how long", "career length", "tenure", "18 years"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2007–Present",
    relatedProjects: [],
    relatedTopics: ["career", "tenure"],
    approvedWording: "I bring 18+ years of product design leadership across the US, Europe, and India."
  },
  {
    id: "fact-status-current",
    category: "status",
    subject: "Current Role and Physical Location",
    exactClaim: "Lead Product Designer at Microsoft in Hyderabad, India.",
    searchKeywords: ["current role", "where do you work", "location", "hyderabad", "india", "current status", "current company"],
    sourceRef: "Profile configuration & ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "May 2025–Present",
    relatedProjects: ["Microsoft Copilot", "Viva Engage"],
    relatedTopics: ["current-job", "location"],
    approvedWording: "I am currently based in Hyderabad, India, working as a Lead Product Designer at Microsoft."
  },
  {
    id: "fact-status-relocation",
    category: "status",
    subject: "Relocation & Leadership Intent",
    exactClaim: "Actively exploring senior design leadership roles in London (UK) and returning to the US.",
    searchKeywords: ["relocation", "relocate", "london", "uk", "us", "united states", "open to move", "moving"],
    sourceRef: "Profile configuration update",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Current (2026)",
    relatedProjects: [],
    relatedTopics: ["relocation", "hiring"],
    approvedWording: "I am actively exploring senior design leadership opportunities in London and returning to the United States."
  },

  // ── Roles & Employment History ──
  {
    id: "fact-role-microsoft",
    category: "role",
    subject: "Microsoft",
    exactClaim: "Product Design Lead at Microsoft (May 2025 – Present) in Hyderabad, India. Leading Copilot adoption design in Viva Engage and Teams integration, directing Engage Analytics.",
    searchKeywords: ["microsoft", "copilot", "viva engage", "viva", "teams", "engage analytics"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "May 2025 – Present",
    relatedProjects: ["Viva Engage", "Copilot Adoption", "Engage Analytics"],
    relatedTopics: ["enterprise-ai", "adoption"],
    approvedWording: "At Microsoft, I lead product design for Copilot Adoption Community experiences across Viva Engage and Teams, scaling usage to 1.5M+ MAU."
  },
  {
    id: "fact-role-oracle",
    category: "role",
    subject: "Oracle",
    exactClaim: "Sr. Principal Product Designer at Oracle (March 2025 – May 2025, Remote). Led design team for AI-powered enterprise finance automation and analytics.",
    searchKeywords: ["oracle", "finance", "reconciliation", "financial operations"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Mar 2025 – May 2025",
    relatedProjects: ["AI Finance"],
    relatedTopics: ["fintech", "enterprise-automation"],
    approvedWording: "At Oracle, I directed UX strategy for AI-driven enterprise financial operations, automating complex multi-tier reconciliation."
  },
  {
    id: "fact-role-google",
    category: "role",
    subject: "Google",
    exactClaim: "Lead UX Designer at Google Cloud Security & Anthos in New York City (October 2021 – January 2024, extended collaboration through 2024). Overhauled Anthos UX, automated security workflows.",
    searchKeywords: ["google", "google cloud", "anthos", "cloud security", "nyc", "new york"],
    sourceRef: "ExperienceTimeline.tsx & Google Case Studies",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Oct 2021 – Jan 2024 / Dec 2024 (See Conflict Report CR-001)",
    relatedProjects: ["Anthos UX Overhaul", "Data Security Posture Mgmt"],
    relatedTopics: ["cloud-security", "developer-tools"],
    approvedWording: "At Google in NYC, I was Lead UX Designer for Google Cloud Security and Anthos, modernizing complex infrastructure workflows to boost adoption by 30% and CSAT by 25%."
  },
  {
    id: "fact-role-mckinsey",
    category: "role",
    subject: "McKinsey & Company",
    exactClaim: "Lead Product Designer at McKinsey & Company (September 2017 – October 2021) in Prague, Czech Republic. Led flagship digital transformations and early conversational AI systems.",
    searchKeywords: ["mckinsey", "prague", "consulting", "conversational ai", "chatbots"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Sep 2017 – Oct 2021",
    relatedProjects: ["Enterprise Digital Transformation", "Conversational AI"],
    relatedTopics: ["consulting", "design-strategy"],
    approvedWording: "At McKinsey in Prague, I led UX strategy for high-impact digital transformations and pioneered early conversational AI solutions for global clients over four years."
  },
  {
    id: "fact-role-cognizant",
    category: "role",
    subject: "Cognizant Technology Solutions",
    exactClaim: "Sr. User Experience Designer at Cognizant (March 2014 – September 2017) in Chennai, India. Mentored UX teams, managed enterprise client delivery.",
    searchKeywords: ["cognizant", "chennai", "senior ux designer"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Mar 2014 – Sep 2017",
    relatedProjects: [],
    relatedTopics: ["enterprise-ux", "mentorship"],
    approvedWording: "At Cognizant, I led and mentored UX squads across design direction, project management, and enterprise stakeholder engagement."
  },
  {
    id: "fact-role-tcs",
    category: "role",
    subject: "Tata Consultancy Services (TCS)",
    exactClaim: "Sr. User Experience Designer at TCS (August 2010 – March 2014) in Mumbai, India. Executed user research, information architecture, prototyping, and usability testing.",
    searchKeywords: ["tcs", "tata consultancy services", "mumbai"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Aug 2010 – Mar 2014",
    relatedProjects: [],
    relatedTopics: ["user-research", "interaction-design"],
    approvedWording: "At TCS, I led end-to-end user-centered design—from field research and information architecture to high-fidelity prototyping and usability testing."
  },
  {
    id: "fact-role-earlier",
    category: "role",
    subject: "Earlier Foundation (Allscripts, Lionbridge, NTTTR)",
    exactClaim: "UI Designer at Allscripts (May 2009 – Aug 2010, Pune), Graphic Designer at Lionbridge (Nov 2007 – May 2009, Chennai), Intern UI Designer at NTTTR (2007).",
    searchKeywords: ["allscripts", "lionbridge", "ntttr", "early career", "first job"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2007 – 2010",
    relatedProjects: [],
    relatedTopics: ["career-origins"],
    approvedWording: "I began my design career in 2007, building core craft foundations across UI, graphic systems, and web interactions at NTTTR, Lionbridge, and Allscripts."
  },

  // ── Education & Certifications ──
  {
    id: "fact-education-degree",
    category: "education",
    subject: "Engineering Degree",
    exactClaim: "Bachelor of Engineering in Computer Science & Engineering, Anna University (2003–2007).",
    searchKeywords: ["education", "degree", "anna university", "college", "computer science", "engineering"],
    sourceRef: "ExperienceTimeline.tsx & profile data",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2003–2007",
    relatedProjects: [],
    relatedTopics: ["computer-science", "engineering"],
    approvedWording: "I hold a degree in Computer Science & Engineering from Anna University (2003–2007), giving me a deep technical foundation when collaborating with engineering teams."
  },
  {
    id: "fact-education-certifications",
    category: "education",
    subject: "Certifications",
    exactClaim: "Certified Usability Analyst (CUA) from Human Factors International (2012), Agile Leadership Journey (New York), Designing the Mobile UX, and Design for Social Innovation & Sustainable Development.",
    searchKeywords: ["certifications", "certified usability analyst", "cua", "hfi", "human factors international", "agile leadership"],
    sourceRef: "ExperienceTimeline.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2012–Present",
    relatedProjects: [],
    relatedTopics: ["usability", "agile"],
    approvedWording: "My credentials include Certified Usability Analyst (CUA) from Human Factors International, plus certifications in Agile Leadership (NYC) and Mobile UX design."
  },

  // ── Global Footprint ──
  {
    id: "fact-location-global-footprint",
    category: "location",
    subject: "Global Cities & Footprint",
    exactClaim: "Lived and worked across Chennai, Amsterdam, Copenhagen, Prague, Warsaw, New York City, and Hyderabad.",
    searchKeywords: ["cities", "countries", "global footprint", "lived", "worked abroad", "europe", "prague", "amsterdam", "copenhagen", "warsaw", "new york"],
    sourceRef: "AboutSection.tsx & profile",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2007–Present",
    relatedProjects: [],
    relatedTopics: ["global-perspective", "mobility"],
    approvedWording: "My design journey spans 18+ years across global innovation hubs including New York City, Prague, Amsterdam, Copenhagen, Warsaw, Chennai, and Hyderabad."
  },

  // ── Contact Destinations ──
  {
    id: "fact-contact-details",
    category: "contact",
    subject: "Contact & Portfolio Access",
    exactClaim: "Email: vikramtheartist@gmail.com, LinkedIn: linkedin.com/in/vikramtheartist, Portfolio: vikramtheartist.com.",
    searchKeywords: ["email", "contact", "reach", "linkedin", "hire", "talk", "resume"],
    sourceRef: "vikramtheartist.com footer",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Permanent",
    relatedProjects: [],
    relatedTopics: ["contact", "outreach"],
    approvedWording: "You can reach me directly at vikramtheartist@gmail.com or on LinkedIn at linkedin.com/in/vikramtheartist."
  }
];
