import { EvidenceAsset } from "./types";

export const EVIDENCE_ASSETS: EvidenceAsset[] = [
  {
    id: "evidence-adopt-playbook",
    title: "ADOPT Framework Playbook Deck",
    assetType: "deck",
    url: "https://www.figma.com/deck/vGd7lTFMt1PeMQTr7dcz7l/ADOPT?node-id=1-125042&t=0hOVNm0DbUaw8jaK-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1",
    internalRoute: "/adopt",
    description: "Interactive playbook deck detailing the 5 stages of AI behavioral adoption.",
    displayLabel: "View ADOPT Playbook",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2024 – Present",
    relatedProjects: ["Copilot Adoption", "ADOPT"],
    relatedTopics: ["frameworks", "playbook"]
  },
  {
    id: "evidence-adoptiq-engine",
    title: "AdoptIQ.ai Live Web Engine",
    assetType: "prototype",
    url: "https://adoptiqai.vercel.app/",
    description: "Production web application demonstrating the AI adoption engine interface.",
    displayLabel: "Open AdoptIQ.ai",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2025 – Present",
    relatedProjects: ["AdoptIQ"],
    relatedTopics: ["web-app", "interactive-demo"]
  },
  {
    id: "evidence-copilot-usecase",
    title: "Microsoft Copilot Adoption Case Study",
    assetType: "case_study_section",
    internalRoute: "/scale-copilot-engage",
    description: "In-depth interactive breakdown of scaling Copilot habits in Viva Engage & Teams.",
    displayLabel: "View Copilot Use Case",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2025 – Present",
    relatedProjects: ["Copilot Adoption"],
    relatedTopics: ["case-study", "copilot"]
  },
  {
    id: "evidence-data-security",
    title: "Data Security Posture Management Prototype",
    assetType: "prototype",
    url: "https://datasecurity-vikram.framer.website/",
    description: "Interactive Framer prototype showcasing cloud security posture management and automated triage.",
    displayLabel: "Open Data Security Prototype",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2022 – 2024",
    relatedProjects: ["Data Security", "Anthos"],
    relatedTopics: ["cloud-security", "framer"]
  },
  {
    id: "evidence-feedback-360-behance",
    title: "Feedback 360° Discovery & Execution Process",
    assetType: "article",
    url: "https://www.behance.net/gallery/98921683/Feedback-360",
    internalRoute: "/feedback-360",
    description: "Published case study covering the 5-day design sprint, user research, and validated prototypes.",
    displayLabel: "View Feedback 360° Case Study",
    sourceRef: "Feedback360Page.tsx & WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Published Archive",
    relatedProjects: ["Feedback 360°"],
    relatedTopics: ["case-study", "behance"]
  },
  {
    id: "evidence-communities-2-deck",
    title: "Viva Engage Communities 2.0 Vision Deck",
    assetType: "deck",
    url: "https://www.figma.com/deck/ELKvu1uZ9wBlg314EFdMVO/Communities-2.0--Hack?node-id=1-16&viewport=-101%2C-140%2C0.65&t=5MqLdsILtEH45MGQ-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1",
    description: "Figma deck highlighting local goal empowerment and social community mechanics.",
    displayLabel: "View Communities 2.0 Deck",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2025",
    relatedProjects: ["Viva Engage Communities"],
    relatedTopics: ["figma-deck", "communities"]
  },
  {
    id: "evidence-helpdesk-slides",
    title: "AI Powered Help-Desk Experience Presentation",
    assetType: "deck",
    url: "https://docs.google.com/presentation/d/e/2PACX-1vQvENFUrPSpj9opoTOxY0pCLjRgFd63Jnu5Ps8BQa4SBmR6Tj_uToYbOo2EoOZS3Dj5kqW2d9gaSXrF/pub",
    description: "Published slide presentation on self-serve predictive help-desk design.",
    displayLabel: "View Help-Desk Deck",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Published Archive",
    relatedProjects: ["AI Powered Help-desk"],
    relatedTopics: ["self-service", "it-support"]
  },
  {
    id: "evidence-notification-xd-slides",
    title: "Notification Experience Design Playbook Presentation",
    assetType: "deck",
    url: "https://docs.google.com/presentation/d/10f2xETw-H17PE4fwk7_gnLniytWco4oBRpC-0JpCjNw/pub",
    description: "Published presentation detailing proactive notification architecture and recommendations.",
    displayLabel: "View Notification Playbook",
    sourceRef: "WorkSection.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "Published Archive",
    relatedProjects: ["Notification Experience Design"],
    relatedTopics: ["notifications", "playbook"]
  },
  {
    id: "evidence-vibe-coding-page",
    title: "Vibe Coding Interactive Gallery",
    assetType: "case_study_section",
    internalRoute: "/vibe-coding",
    description: "Interactive portfolio section exploring rapid AI-assisted coding and design engineering.",
    displayLabel: "Explore Vibe Coding",
    sourceRef: "VibeCodingPage.tsx",
    verificationStatus: "verified",
    publicApprovalStatus: "approved",
    lastReviewedDate: "2026-09-08",
    applicableTimePeriod: "2024 – Present",
    relatedProjects: ["Vibe Coding"],
    relatedTopics: ["vibe-coding", "design-engineering"]
  }
];
